//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace team_profi
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRatings
    {
        public int RatingID { get; set; }
        public int StudentID { get; set; }
        public int TotalPoints { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
